//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubstitutionCipher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubstitutionCipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TION 13168375
        ///NTHE 11234972
        ///THER 10218035
        ///THAT 8980536
        ///OFTH 8132597
        ///FTHE 8100836
        ///THES 7717675
        ///WITH 7627991
        ///INTH 7261789
        ///ATIO 7104943
        ///OTHE 6900574
        ///TTHE 6553056
        ///DTHE 6470280
        ///INGT 6461147
        ///ETHE 6135216
        ///SAND 5996705
        ///STHE 5748611
        ///HERE 5630500
        ///THEC 5466071
        ///MENT 4968019
        ///THEM 4911484
        ///RTHE 4862875
        ///THEP 4458634
        ///FROM 4361347
        ///THIS 4344608
        ///TING 4291641
        ///THEI 4217321
        ///NGTH 4162753
        ///IONS 4045101
        ///ANDT 4020364
        ///ONTH 3976144
        ///TOTH 3911094
        ///EDTO 3886447
        ///THEF 3873133
        ///THEY 3809433
        ///HAVE 3735139
        ///EDTH 3699013
        ///INGA 3675933
        ///NDTH 3619148
        ///TH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Quadgrams_English {
            get {
                return ResourceManager.GetString("Quadgrams_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the	82103550112
        ///ing	43727954927
        ///and	43452082914
        ///ion	39907843075
        ///tio	32705432538
        ///ent	31928292897
        ///for	26276145239
        ///ati	25312331919
        ///ter	21635845251
        ///ate	19978168727
        ///ers	18428556963
        ///res	16905804845
        ///her	16817683835
        ///est	16153205958
        ///com	16125312457
        ///pro	15952570392
        ///ere	15305553822
        ///all	15280030691
        ///int	15254348969
        ///men	15240388304
        ///you	15014247063
        ///ons	14765503549
        ///our	14731181262
        ///con	14345102137
        ///are	14170861835
        ///tha	13970309343
        ///ver	13912756928
        ///ess	13754386504
        ///thi	13367612267
        ///rea	13285735421
        ///st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trigrams_English {
            get {
                return ResourceManager.GetString("Trigrams_English", resourceCulture);
            }
        }
    }
}
